<%@ Page Title="Terms & Conditions" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Terms.aspx.cs" Inherits="MachineQuote.About" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <h2><%: Title %>.</h2>
    <h3> <%: DateTime.Now.Year %> </h3>
    <h1> User Agreement</h1>

    <p>THIS USER AGREEMENT describes the terms according to which, and conditions subject to which, MachineQuote, an Colorado limited liability company, will grant to you the right to use “MachineQuote”, its request‑for‑proposal management product. Capitalized terms used in this User Agreement are defined in Section 6.</p>
    <p>By clicking “I Agree”, you acknowledge that you intend to enter into this Agreement, which is a legally binding and enforceable contract. If you do not intend to be so bound, you should not click “I Agree” and discontinue use of this website. In consideration of these premises, and the representations, warranties and covenants set forth in this Agreement, and for other good and valuable consideration, the receipt and sufficiency of which you acknowledge, by clicking “I Agree” you agree with MachineQuote as to that set forth below.</p>
    <h2>1. License Terms.</h2>
    <p>1.1 MachineQuote hereby grants to you a limited, nonexclusive and nontransferable right and license for you to use the Software Product in accordance with this Agreement.</p>
    <p>1.2 You may not (a) authorize or license any other party to use the Software Product or any part thereof (whether directly or indirectly), (b) modify or customize the Software Product or any part thereof, (c) create any derivative works in, or based on, the Software Product or any part thereof, (d) print, copy or reproduce the Software Product or any part thereof, (e) distribute, license, sublicense, promote, distribute, market, sell, lease, assign, convey, transfer or transmit the Software Product or any part thereof (whether physically or electronically) or (f) decompile, disassemble, decode or otherwise reverse engineer the Software Product or any part thereof.</p>
    <p>1.3 All right, title and interest in and to each of the following is, shall be and at all times shall remain the exclusive property of MachineQuote and any third-parties whose software programs may have been, or may be, incorporated into the Software Product: (a) the Software Product, the Object Code and the Source Code, (b) any software, software modifications, derivative works, processes, configurations, system referenced data, procedures and other intellectual property rights relating to data processing and information technology developed or held by either Party from its use of the Software Product or in the performance of its obligations according to this Agreement and (c) all copyright, trademark, patent, trade secret and intellectual property rights in the Software Product. MachineQuote, on behalf of itself and any third-parties with software that may have been, or may be, incorporated into the Software Product, reserves all of its, and all of such third-parties’, rights in the same.</p>
    <h2>2. Representations & Warranties.</h2>
    <p>2.1 MachineQuote hereby represents and warrants to you that (a) it has the full right, power and authority to enter into, and fully perform its obligations according to, this Agreement and (b) MachineQuote has the full right, power and authority to grant to you the rights and licenses described herein.</p>
    <p>2.2 You hereby represent and warrant to MachineQuote that you have the full right, power, authority and capacity to enter into, and fully perform your obligations according to, this Agreement.</p>
    <h2>3. Indemnification; Limitations on Liability; Remedies.</h2>
    <p>3.1 You shall indemnify, defend and hold harmless MachineQuote, and its members, managers, officers, employees, agents and affiliates from and against any liabilities, costs, fees and/or damages that arise out of any claim for damages resulting from (a) any material inaccuracy or breach of the representations and warranties made by you in Section 2.2, (b) any material breach of a covenant made by you in this Agreement and/or (c) any material failure to perform, or any material failure to comply with, your obligations according to this Agreement.</p>
    <p>3.2 THE SOFTWARE PRODUCT IS PROVIDED BY MachineQuote ON AN “AS-IS” BASIS. ALL OTHER WARRANTIES, WHETHER ORAL OR WRITTEN, EXPRESS OR IMPLIED OR CONTRACTUAL OR STATUTORY, ARE EXPRESSLY DISCLAIMED. WITHOUT LIMITATION, MachineQuote NEITHER REPRESENTS AND WARRANTS, NOR COVENANTS, THAT (a) THE OPERATION AND/OR USE OF THE SOFTWARE PRODUCT WILL BE UNINTERRUPTED OR ERROR-FREE, (b) THE SOFTWARE PRODUCT WILL PERFORM IN EVERY OPERATING ENVIRONMENT, (c) ALL DEFICIENCIES OR ERRORS IN THE SOFTWARE PRODUCT ARE CAPABLE OF CORRECTION OR (d) THE SOFTWARE PRODUCT MEETS THE REQUIREMENTS OF ANY PARTY WHATSOEVER. THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE SPECIFICALLY DISCLAIMED.</p>
    <p>3.3 YOU ACKNOWLEDGE THAT, WITHOUT LIMITATION OF THAT OTHERWISE SET FORTH HEREIN, MachineQuote IS IN NO WAY RESPONSIBLE (a) FOR THE OUTCOME RESULTING FROM ANY SUBMISSION YOU MAKE, OR BID YOU SUBMIT, USING THE SOFTWARE PRODUCT, (b) FOR DETERMINATIONS MADE BY ANY PARTY REQUESTING A PROPOSAL, THE SUBMISSION OF A BID OR OTHERWISE USING THE SOFTWARE PRODUCT, INCLUDING ANY SUCH PARTY’S DECISION TO LIMIT, EXPAND, SUSPEND, TERMINATE OR OTHERWISE CHANGE ITS USE OF THE SOFTWARE PRODUCT, WHETHER ANY OF THE SAME IS MADE BEFORE, DURING OR AFTER ANY SUBMISSION IS MADE, (c) FOR DETERMINATIONS MADE BY ANY PARTY REQUESTING A PROPOSAL, THE SUBMISSION OF A BID OR OTHERWISE OR ANY SUCH PARTY’S DECISION NOT TO, OR FAILURE TO MAKE, A DETERMINATION, WHETHER USING THE SOFTWARE PRODUCT OR OTHERWISE, (D) FOR THE TRANSMISSION, PRIOR TO RECEIPT BY MachineQuote, OF ALL INFORMATION YOU PROVIDE, OR OTHERWISE INPUT, USING THE SOFTWARE PRODUCT AND (e) IF YOU ARE UNABLE TO ACCESS THE SOFTWARE PRODUCT AS A RESULT OF TECHNICAL OR OTHER DIFFICULTIES RESULTING FROM YOUR HARDWARE OR INTERNET CONNECTION.</p>
    <p>3.4 NOTWITHSTANDING ANY OTHER PROVISION OF THIS AGREEMENT, THE AGGREGATE DAMAGES THAT MAY BE RECOVERED BY YOU MAY NOT EXCEED AN AMOUNT EQUAL TO THE FEES PAID TO MachineQuote BY YOU IN THE CALENDAR YEAR IN WHICH A CLAIM IS BROUGHT.</p>
    <p>3.5 NEITHER PARTY MAY BE HELD LIABLE TO THE OTHER, OR TO ANY OTHER PARTY, FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY OR PUNITIVE DAMAGES (INCLUDING LOST OR ANTICIPATED REVENUES OR PROFITS) ARISING FROM ANY CLAIM RELATING DIRECTLY OR INDIRECTLY TO THIS AGREEMENT, WHETHER BASED ON WARRANTY, CONTRACT OR TORT (WHETHER UNDER A THEORY OF NEGLIGENCE, STRICT LIABILITY OR OTHERWISE), EVEN IF AN AUTHORIZED REPRESENTATIVE OF SUCH PARTY IS ADVISED OF THE LIKELIHOOD OR POSSIBILITY THEREOF.</p>
    <p>3.6 EACH PARTY ACKNOWLEDGES THAT THE OTHER PARTY HAS RELIED UPON THE LIMITATIONS ON LIABILITY SET FORTH IN THIS SECTION 3 AND, BUT FOR THEIR INCLUSION HEREIN, WOULD NOT HAVE ENTERED INTO THIS AGREEMENT.</p>
    <p>3.7 You further acknowledge (a) that MachineQuote will suffer irreparable harm, and that the amount of monetary damages would be extremely difficult or impossible to calculate, if you breach your obligations according to this Agreement and (b) that if you breach your obligations according to this Agreement, MachineQuote may seek, and you covenant not to dispute any attempt by MachineQuote to seek, injunctive relief without proving actual damages and (c) that remedies sought by MachineQuote in accordance with this Section 3.7 shall be in addition to, and without limitation of, any other rights to which MachineQuote may be entitled according to this Agreement or Law.</p>
    <h2>4. Your Obligations.</h2>
    <p>4.1 You shall (a) use the Software Product in accordance with this Agreement and all applicable Laws, (b) promptly report to MachineQuote any flaws, errors, bugs, defects or other problems in or with the Software Product that you identify, (c) obtain the explicit consent of any party whose personally identifiable information you are inputting into the Software Product or, if such party is an individual who is under the age of 13, the explicit consent of such person’s parent or legal guardian, (d) comply with the applicable provisions of the Privacy Policy, (e) prior to inputting, or otherwise delivering to MachineQuote, any content, data, material or other information whatsoever, obtain the consent of any party from which consent may be required to so input or otherwise deliver to MachineQuote any of the same and (f) otherwise comply with the provisions of this Agreement.</p>
    <p>4.2 You may not (a) use the Software Product to send unauthorized, untargeted or unwanted messages, communications, advertisements or other promotional materials, (b) use automated software, scripts or other methods of accessing or using the Software Product without MachineQuote’s consent, (c) scrape from, or otherwise use, the Software Product any content, data, material submitted or other information whatsoever or (d) impersonate another party, misrepresent your identity or affiliation with another party or otherwise inaccurately or incorrectly describe yourself.</p>
    <h2>5. Term & Termination.</h2>
    <p>5.1 MachineQuote may terminate this Agreement for any reason or no reason, at any time, with or without notice.</p>
    <p>5.2 Immediately upon the termination of this Agreement, you will have no further right, title or interest in the Software Product or any part thereof, including any license in either of the same.</p>
    <p>5.3 The provisions of Sections 1.2, 1.3, 3 and 4, the provisions of this Section 5 and, as and where applicable, the provisions of Sections 6 and 7 shall survive any termination of this Agreement.</p>
    <h2>6. Defined Terms.</h2>
    <p>“Agreement” means this User Agreement entered into by and between you and MachineQuote.</p>
    <p>“Law” means any statute, law, ordinance, regulation, rule, code, order, constitution, treaty, common law, judgment, decree, other requirement or rule of law of any federal, state or local government or any agency or instrumentality thereof and any arbitrator, court or tribunal of competent jurisdiction.</p>
    <p>“Object Code” means the machine-readable computer software code relating to the Software Product, including any Update or Upgrade, which code is substantially in binary form that is directly executable by a computer after processing without compilation or assembly.</p>
    <p>“Party” means either MachineQuote or you.</p>
    <p>“Privacy Policy” means the MachineQuote Privacy Policy, a copy of which may be found at https://need, as it may from time-to-time be amended by MachineQuote in its sole discretion.</p>
    <p>“MachineQuote” means MachineQuote, an Ohio limited liability company.</p>
    <p>“Software Product” means MachineQuote’s request-for-proposal management product made available to you by MachineQuote, including any third-party software embedded therein, any Updates and any Upgrades.</p>
    <p>“Source Code” means (a) the computer software code comprising the statements, instructions and data relating to the Software Product displayed in a form readable and understandable by a programmer of ordinary skill, (b) technical documentation and specifications relating to the Software Product, including a description of the tools used to develop and maintain the Software Product, the compiler or assembler and compilation and execution procedures and (c) the computer software code, technical documentations and specifications relating to any Updates or Upgrades.</p>
    <p>“Update” means any update, feature release (e.g., 2.0 to 2.1), patch release (e.g., 2.0.1 to 2.0.2), maintenance release, bug fix or modified form of the Software Product that performs comparable or improved functionality and which is not an Upgrade.</p>
    <p>“Upgrade” means any new version or major release (e.g., 2.0 to 3.0) of the Software Product, including any changes to the Software Product that (a) substantially increase the speed, efficiency or ease of use of the Software Product or (b) add additional capabilities to, or otherwise improve the functions of, the Software Product.</p>
    <h2>7. General Provisions.</h2>
     <p>7.1 Any notice required, or permitted, to be delivered by MachineQuote hereunder shall be deemed delivered to you when delivered to the email address you provided to MachineQuote.</p>
    <p>7.2 This Agreement, when taken together with the Privacy Policy, constitutes the entire agreement between the Parties as to the subject matter hereof and supersedes all prior documents, negotiations and drafts of such Parties with respect to such subject matter, whether written or verbal. No provision of this Agreement may be construed against either Party by reason of the drafting or preparation thereof.</p>
    <p>7.3 MachineQuote may change this Agreement from time to time and any such change shall be effective upon your clicking “I Agree” when requested to do so after any such change is made.</p>
    <p>7.4 Any provision of this Agreement may be waived, terminated or discharged with MachineQuote’s consent at any time and in its sole discretion. The failure of MachineQuote to insist upon the performance of any of the terms or conditions contained in this Agreement and/or to exercise any right hereunder, may not be construed as a waiver or relinquishment of the future performance of any such term or condition or the future exercise of such rights.</p>
    <p>7.5 If any provision of this Agreement is held to be unenforceable, the Parties shall renegotiate each such provision in good faith in order to maintain the economic position enjoyed by each Party prior to such holding with respect to each such provision rendered unenforceable. If the Parties cannot agree upon an enforceable replacement for such provision, then (a) such provision shall be excluded from this Agreement, (b) the balance of this Agreement shall be interpreted as if such provision were so excluded and (c) thereafter, this Agreement shall be enforceable in accordance with its terms.</p>
    <p>7.6 You may not assign this Agreement, in whole or in part, by operation of Law or otherwise, without MachineQuote’s prior written consent. Any attempt to do so shall be deemed null and void and of no legal force or effect. This Agreement shall be binding upon and shall inure to the benefit of the Parties’ successors and permitted assigns.</p>
    <p>7.7 Neither Party may be held liable for its failure to perform hereunder, or for any loss or damage, due to causes beyond its reasonable control, including governmental requirements, inability to obtain required export licenses, work stoppages, fire, civil disobedience, embargo, war, terrorism, riots, rebellions, earthquakes, strikes, floods, water and the elements, inability to secure equipment, raw materials or transport or similar occurrences.</p>
    <p>7.8 Unless the context clearly requires otherwise, (a) the singular shall be deemed to include the plural and vice versa, (b) reference to any agreement, document or instrument shall be deemed to refer to such agreement, document or instrument as may be amended or modified and in effect from time to time, (c) “hereunder”, “hereof”, “hereto” and words similar thereto shall be deemed references to this Agreement as a whole and not to any particular provision hereof, (d) the words “include” and “including” shall be deemed to mean “without limitation” and shall be interpreted not to limit the generality of any description preceding such term, (e) with respect to the determination of any period of time, “from” means “from and including” and “to” means “to but excluding” and (f) any reference to a “Section” in this Agreement shall be construed as a reference to a section of this Agreement.</p>
    <p>7.9 Neither this Agreement nor any provision contained herein may be construed as creating or constituting a partnership, joint venture or agency relationship between the Parties. The relationship created hereby is strictly that of licensor and licensee. For the avoidance of doubt, neither Party has the power or authority to, and no Party may, assume or create any obligation or responsibility on behalf of the other.</p>
    <p>7.10 This Agreement shall be deemed fully and finally executed as soon as you click “I Agree” and any copy hereof, together with evidence of your having done so, shall be deemed an original and all of which together shall constitute a single instrument.</p>
        
</asp:Content>
